POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "fullname": "Sundy Shwe",
    "email": "sundy@miu.edu",
    "password": "binnie"
}
###
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "sundy@miu.edu",
    "password": "binnie"
}